version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec jekyll serve --livereload --host=0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
      - 35729:35729
