version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    # host flag allows Jekyll server to be accessed from outside the container
    command: bundle exec jekyll serve --livereload --host=0.0.0.0
    # volume allows changes to be seen on localhost immediately instead of having to delete and rebuild image
    volumes:
      - .:/usr/src/app
    # 35729 is the port for livereload
    ports:
      - 4000:4000
      - 35729:35729
